const portfolio = [
  { id: 1, title: "Shinsegae E&C", type: "Standard Web", skill: "html / css / jquery", info: "신세계 E&C 사이트 메인 페이지 리뉴얼", font: "Noto Sans KR", color: ["#da2128", "#fff"], src: process.env.PUBLIC_URL + "/images/project02.jpg", link: "http://mokdanbi.github.io/project02", number: "project01" },
  { id: 2, title: "Salady", type: "Standard Web", skill: ["html / css / jquery"], info: "샐러디 사이트 메인 페이지 리뉴얼", font: "Bowlby One / Pretendard", color: ["#17633d", "#e7efeb", "#333"], src: process.env.PUBLIC_URL + "/images/project03.jpg", link: "http://mokdanbi.github.io/project03", number: "project02" },
  { id: 3, title: "hince", type: "Standard Web", skill: ["html / css / jquery"], info: "hince 사이트 메인 페이지 리뉴얼", font: "DM Serif Text / Pretendard", color: ["#98625f", "#ebd1b9", "#fff"], src: process.env.PUBLIC_URL + "/images/project04.jpg", link: "http://mokdanbi.github.io/project04", number: "project03" },
  { id: 4, title: "object", type: "Responsive Web", skill: ["html / css / jquery"], info: "object 사이트 메인 페이지 리뉴얼 (반응형)", font: "Kanit / Pretendard", color: ["#005caa", "#fff"], src: process.env.PUBLIC_URL + "/images/project05.jpg", link: "http://mokdanbi.github.io/project05", number: "project04" },
  { id: 5, title: "CESCO", type: "Standard Web", skill: ["html / css / jquery"], info: "CESCO 사이트 메인 페이지 리뉴얼", font: "DM Serif Display / Pretendard", color: ["#333", "e30613", "#fff"], src: process.env.PUBLIC_URL + "/images/project06.jpg", link: "http://mokdanbi.github.io/project06", number: "project05" },
  { id: 6, title: "PODO", type: "Responsive Web", skill: ["html / css / jquery"], info: "PODO 사이트 메인 페이지 리뉴얼 (반응형)", font: "Paytone One / Pretendard", color: ["#f7f4ec", "#d8312d", "#000"], src: process.env.PUBLIC_URL + "/images/project07.jpg", link: "http://mokdanbi.github.io/project07", number: "project06" },
  { id: 7, title: "Ananti Hilton Busan", type: "Responsive Web", skill: ["html / css / jquery / javascript"], info: "Ananti Hilton Busan 사이트 메인 페이지 리뉴얼 (반응형)", font: "Noto Serif KR / Dancing Script", color: ["#0d2645", "#cbdbf5", "#163153"], src: process.env.PUBLIC_URL + "/images/project08.jpg", link: "http://mokdanbi.github.io/project08", number: "project07" },
  { id: 8, title: "검색어를 입력하세요 WWW", type: "Standard Web", skill: ["html / css / javascript"], info: "드라마 '검색어를 입력하세요 www' 소개 사이트 메인 페이지 제작", font: "ELAND_Nice_M / InkLipquid / Pretendard", color: ["#495496", "#333", "#fff"], src: process.env.PUBLIC_URL + "/images/project09.jpg", link: "http://mokdanbi.github.io/project09", number: "project08" },
  { id: 9, title: "MIDAS", type: "Standard Web", skill: ["html / css / javascript / react"], info: "인테리어 회사 'MIDAS' 소개 사이트 메인 페이지 제작", font: "Lato / Pretendard", color: ["#333", "#ddd", "#fff"], src: process.env.PUBLIC_URL + "/images/project10.jpg", link: "https://mokdanbi.github.io/project10_react/", number: "project09" },
  { id: 10, title: "두끼", type: "Standard Web", skill: ["html / css / javascript / react"], info: "리액트를 이용한 '두끼' 홈페이지 제작", font: "Pretendard", color: ["#ff671b", "#282828", "#fff"], src: process.env.PUBLIC_URL + "/images/project11.jpg", link: "https://mokdanbi.github.io/project11_react/", number: "project10" },
]

export { portfolio };